controllers/AdministrarController.php
<?php

namespace app\controllers;

use Yii;
use app\models\ComponentesCn;
use app\models\ComponentesCnSearch;
use app\models\CadastroExercicio;
use app\models\Exercicios;
use app\models\ExerciciosSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use yii\web\ForbiddenHttpException;
use app\models\UploadForm;
use yii\web\UploadedFile;

/**
 * AdminController implements the CRUD actions for ComponentesCn model.
 */
class AdministrarController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => [
                            'index',
                            'componentes-cn-index',
                            'componentes-cn-view',
                            'componentes-cn-create',
                            'componentes-cn-update',
                            'componentes-cn-delete',
                            'exercicios-index',
                            'exercicios-view',
                            'exercicios-create',
                            'exercicios-update',
                            'exercicios-delete',
                            'cadastrar-exercicio',
                            'migrar',
                        ],
                        'allow' => true,
                        'roles' => ['admin'],
                    ]                 
                ],
                'denyCallback' => function ($rule, $action) {
                    return $action->controller->redirect('/site/acesso-negado');
                }
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'componentes-cn-delete' => ['POST'],
                ],
                'actions' => [
                    'exercicios-delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all ComponentesCn models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new ComponentesCnSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('componentesCnIndex', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /*

            CADASTRO DE COMPONENTES CURRICULARES 
            DE COMPUTACAO NUMERICA
    */

    /**
     * Lists all ComponentesCn models.
     * @return mixed
     */
    public function actionComponentesCnIndex()
    {
        $searchModel = new ComponentesCnSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('componentesCnIndex', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single ComponentesCn model.
     * @param integer $id
     * @return mixed
     */
    public function actionComponentesCnView($id)
    {
        return $this->render('componentesCnView', [
            'model' => $this->findModelComponentesCn($id),
        ]);
    }

    /**
     * Creates a new ComponentesCn model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionComponentesCnCreate()
    {
        $model = new ComponentesCn();

        if ($model->load(Yii::$app->request->post())) {
            $model->user_id = Yii::$app->user->id;
            if ($model->save()){
                return $this->redirect(['componentes-cn-view', 'id' => $model->id]);    
            }        
        } else {
            return $this->render('componentesCnCreate', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing ComponentesCn model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionComponentesCnUpdate($id)
    {
        $model = $this->findModelComponentesCn($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['componentes-cn-view', 'id' => $model->id]);
        } else {
            return $this->render('componentesCnUpdate', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing ComponentesCn model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionComponentesCnDelete($id)
    {
        $this->findModelComponentesCn($id)->delete();

        return $this->redirect(['componentes-cn-index']);
    }

    /**
     * Finds the ComponentesCn model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return ComponentesCn the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModelComponentesCn($id)
    {
        if (($model = ComponentesCn::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

    /*

            CADASTRO DE EXERCICIOS DO MULTIPROVA

    */

    /**
     * Creates a new ComponentesCn model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCadastrarExercicio()
    {
        $model = new CadastroExercicio();

        if ($model->load(Yii::$app->request->post())) {
            
            $model->arquivo = UploadedFile::getInstance($model, 'arquivo');            
            $uploadOk = $model->upload();

            if ($uploadOk === true) {
                // file is uploaded successfully
                // Insere as informacoes no BD
                $resumo = $model->gravarExercicio();                   
            }             
            return $this->render('cadastrarExercicioOk', ['model' => $model, 'resumo' => $resumo]);

        } else {
            return $this->render('cadastrarExercicio', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Lists all Exercicios models.
     * @return mixed
     */
    public function actionExerciciosIndex()
    {
        $searchModel = new ExerciciosSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('exerciciosIndex', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Exercicios model.
     * @param integer $id
     * @return mixed
     */
    public function actionExerciciosView($id)
    {
        return $this->render('exerciciosView', [
            'model' => $this->findModelExercicios($id),
        ]);
    }

    /**
     * Creates a new Exercicios model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionExerciciosCreate()
    {
        $model = new CadastroExercicio();

        if ($model->load(Yii::$app->request->post())) {
            
            $model->arquivo = UploadedFile::getInstance($model, 'arquivo');            
            $uploadOk = $model->upload();

            if ($uploadOk === true) {
                // file is uploaded successfully
                // Insere as informacoes no BD
                $resumo = $model->gravarExercicio();    
            }             
            return $this->render('exerciciosCreated', ['model' => $model, 'resumo' => $resumo]);

        } else {
            return $this->render('exerciciosCreate', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing Exercicios model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionExerciciosUpdate($id)
    {
        $model = $this->findModelExercicios($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['exercicios-view', 'id' => $model->id]);
        } else {
            return $this->render('exerciciosUpdate', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Exercicios model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionExerciciosDelete($id)
    {
        $this->findModelExercicios($id)->delete();

        return $this->redirect(['exercicios-index']);
    }

    /**
     * Migrar Exercicios.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
    */
    
    public function actionMigrar($id)
    {       
        $modelCadastroExercicios = New CadastroExercicio();
        if ($modelCadastroExercicios->gerarImagens($id)) 
        echo "Sucesso";                
    }  
    /**
     * Finds the Exercicios model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Exercicios the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModelExercicios($id) 
    {
        if (($model = Exercicios::findOne($id)) !== null) {
            return $model;
        } else {

views/administrar/cadastrarExercicio.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;


/* @var $this yii\web\View */
/* @var $model frontend\models\ComponentesCn */

$this->title = 'Cadastrar novo exercício';
$this->params['breadcrumbs'][] = ['label' => 'Componentes Cns', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>


<div class="page-title">
  <div class="title_left">
    <h3><?= Html::encode($this->title) ?></h3>
  </div>
</div>
<div class="clearfix"></div>
<div class="row">
  <div class="col-md-12 col-sm-12 col-xs-12">
    <div class="x_panel">
      <div class="x_title">
        <h2>Importando arquivo do Multiprova:</h2>
        <ul class="nav navbar-right panel_toolbox">
          <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
          </li>
        </ul>
        <div class="clearfix"></div>
      </div>
      <div class="x_content2">
        <?php $form = ActiveForm::begin(['options' => ['enctype' => 'multipart/form-data']]); ?>
          <?= $form->field($model, 'descricao')->textInput() ?>
          <?= $form->field($model, 'arquivo')->fileInput() ?>
          <?= Html::activeHiddenInput($model,'comImagens',['value' => 0]) ?>

          <div class="ln_solid"></div>

          <div class="form-group">
	        <?= Html::submitButton('Cadastrar exercício', ['class' => 'btn btn-success']) ?>
	      </div>
        <?php ActiveForm::end(); ?>
      </div>
    </div>
  </div>
</div>
<div class="clearfix"></div>
<div class="row">
  <div class="col-md-12 col-sm-12 col-xs-12">
    <div class="x_panel">
      <div class="x_title">
        <h2>Importando a questão instanciada do Multiprova:</h2>
        <ul class="nav navbar-right panel_toolbox">
          <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
          </li>
        </ul>
        <div class="clearfix"></div>
      </div>
      <div class="x_content2">
        <?php $form = ActiveForm::begin(); ?>
          <?= $form->field($model, 'descricao')->textInput() ?>
          <?= $form->field($model, 'idAvaliacao')->textInput() ?>
          <?= Html::activeHiddenInput($model,'comImagens',['value' => 1]) ?>

          <div class="ln_solid"></div>
          
          <div class="form-group">
	        <?= Html::submitButton('Cadastrar exercício', ['class' => 'btn btn-success']) ?>
	      </div>
        <?php ActiveForm::end(); ?>
      </div>
    </div>
  </div>
</div>

views/administrar/componentesCnCreate.php
<?php

use yii\helpers\Html;
use yii\widgets\Breadcrumbs;
use app\widgets\Alert;

/* @var $this yii\web\View */
/* @var $model frontend\models\ComponentesCn */

$this->title = 'Novo Componente CN';
$this->params['breadcrumbs'][] = ['label' => 'Componentes', 'url' => ['componentes-cn-index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="componentes-cn-create">

    <?= Breadcrumbs::widget([
        'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
    ]) ?>
    <?= Alert::widget() ?>

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('componentesCn_Form', [
        'model' => $model,
    ]) ?>

</div>

views/administrar/componentesCnIndex.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yiister\gentelella\widgets\grid\GridView;
use yii\widgets\Breadcrumbs;
use app\widgets\Alert;
/* @var $this yii\web\View */
/* @var $searchModel frontend\models\ComponentesCnSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Cadastros de Componentes de CN';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="componentes-cn-index">

    <?= Breadcrumbs::widget([
        'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
    ]) ?>
    <?= Alert::widget() ?>

    <h1><?= Html::encode($this->title) ?></h1>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <p>
        <?= Html::a('Cadastar novo componente', ['componentes-cn-create'], ['class' => 'btn btn-success']) ?>
    </p>
    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        //'filterModel' => $searchModel,
        'columns' => [
            //['class' => 'yii\grid\SerialColumn'],

            //'id',
            //'user_id',
            'codigo',
            'nome',
            //'created_at',
            // 'updated_at',

            [
                'class' => 'yii\grid\ActionColumn',
                'urlCreator' => function ($action, $model, $key, $index, $thisa) {
                    //return string;
                    if ($action === "view"){
                        return Url::toRoute(['administrar/componentes-cn-view', 'id' => $key]);
                    }
                    if ($action === "update"){
                        return Url::toRoute(['administrar/componentes-cn-update', 'id' => $key]); 
                    }
                    if ($action === "delete"){
                        return Url::toRoute(['administrar/componentes-cn-delete', 'id' => $key]);
                    }
                },
            ],
        ],
    ]); ?>
</div>

views/administrar/componentesCnUpdate.php
<?php

use yii\helpers\Html;
use yii\widgets\Breadcrumbs;
use app\widgets\Alert;
/* @var $this yii\web\View */
/* @var $model frontend\models\ComponentesCn */

$this->title = 'Atualizar componente: ' . $model->nome;
$this->params['breadcrumbs'][] = ['label' => 'Componentes', 'url' => ['componentes-cn-index']];
$this->params['breadcrumbs'][] = ['label' => $model->codigo, 'url' => ['componentes-cn-view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Atualizar';
?>

<div class="componentes-cn-update">

    <?= Breadcrumbs::widget([
        'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
    ]) ?>
    <?= Alert::widget() ?>

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('componentesCn_Form', [
        'model' => $model,
    ]) ?>

</div>

views/administrar/componentesCnView.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;
use yii\widgets\Breadcrumbs;
use app\widgets\Alert;
/* @var $this yii\web\View */
/* @var $model frontend\models\ComponentesCn */

$this->title = $model->codigo.' - '.$model->nome;
$this->params['breadcrumbs'][] = ['label' => 'Componentes', 'url' => ['componentes-cn-index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="componentes-cn-view">
    <?= Breadcrumbs::widget([
        'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
    ]) ?>
    <?= Alert::widget() ?>

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Atualizar', ['componentes-cn-update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Excluir', ['componentes-cn-delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Tem certeza que deseja apagar este item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            //'id',
            //'user_id',
            'codigo',
            'nome',
            //'created_at',
            //'updated_at',
        ],
        
    ]) ?>

</div>

views/administrar/componentesCn_Form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model frontend\models\ComponentesCn */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="componentes-cn-form">

    <?php $form = ActiveForm::begin(); ?>

    <!--
    <?= $form->field($model, 'user_id')->textInput() ?>
	-->
    <?= $form->field($model, 'codigo')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'nome')->textInput(['maxlength' => true]) ?>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'Criar' : 'Atualizar', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/administrar/componentesCn_Search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model frontend\models\ComponentesCnSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="componentes-cn-search">

    <?php $form = ActiveForm::begin([
        'action' => ['componentes-cn-index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'user_id') ?>

    <?= $form->field($model, 'codigo') ?>

    <?= $form->field($model, 'nome') ?>

    <?= $form->field($model, 'created_at') ?>

    <?php // echo $form->field($model, 'updated_at') ?>

    <div class="form-group">
        <?= Html::submitButton('Buscar', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/administrar/exerciciosCreate.php
 <?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\widgets\Breadcrumbs;
use app\widgets\Alert;

/* @var $this yii\web\View */
/* @var $model frontend\models\ComponentesCn */

$this->title = 'Cadastrar novo exercício';
$this->params['breadcrumbs'][] = ['label' => 'Exercícios', 'url' => ['exercicios-index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="exercicios-create">
	
	<?= Breadcrumbs::widget([
	    'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
	]) ?>
	<?= Alert::widget() ?>

	<div class="clearfix"></div>
	<div class="row">
	  <div class="col-md-12 col-sm-12 col-xs-12">
	    <div class="x_panel">
	      <div class="x_title">
	        <h2>Importando arquivo do Multiprova:</h2>
	        <ul class="nav navbar-right panel_toolbox">
	          <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
	          </li>
	        </ul>
	        <div class="clearfix"></div>
	      </div>
	      <div class="x_content2">
	        <?php $form = ActiveForm::begin(['options' => ['enctype' => 'multipart/form-data']]); ?>
	          <?= $form->field($model, 'descricao')->textInput() ?>
	          <?= $form->field($model, 'arquivo')->fileInput() ?>
	          <?= Html::activeHiddenInput($model,'comImagens',['value' => 0]) ?>

	          <div class="ln_solid"></div>

	          <div class="form-group">
		        <?= Html::submitButton('Cadastrar Exercício', ['class' => 'btn btn-success']) ?>
		      </div>
	        <?php ActiveForm::end(); ?>
	      </div>
	    </div>
	  </div>
	</div>
	<!--
	<div class="clearfix"></div>
	<div class="row">
	  <div class="col-md-12 col-sm-12 col-xs-12">
	    <div class="x_panel">
	      <div class="x_title">
	        <h2>Importando a questão instanciada do Multiprova: asdf asd</h2>
	        <ul class="nav navbar-right panel_toolbox">
	          <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
	          </li>
	        </ul>
	        <div class="clearfix"></div>
	      </div>
	      <div class="x_content2">
	        <?php $form = ActiveForm::begin(); ?>
	          <?= $form->field($model, 'descricao')->textInput() ?>
	          <?= $form->field($model, 'idAvaliacao')->textInput() ?>
	          <?= Html::activeHiddenInput($model,'comImagens',['value' => 1]) ?>

	          <div class="ln_solid"></div>
	          
	          <div class="form-group">
		        <?= Html::submitButton('Cadastrar exercício', ['class' => 'btn btn-success']) ?>
		      </div>
	        <?php ActiveForm::end(); ?>
	      </div>
	    </div>
	  </div>
	</div>
	-->
</div>

views/administrar/exerciciosCreated.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;
use yii\widgets\Breadcrumbs;
use app\widgets\Alert;

/* @var $this yii\web\View */
/* @var $model frontend\models\ComponentesCn */

$this->title = 'Resultado do processamento:';
$this->params['breadcrumbs'][] = ['label' => 'Exercícios', 'url' => ['exercicios-index']];
$this->params['breadcrumbs'][] = 'Resultado';
?>

  <?= Breadcrumbs::widget([
      'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
  ]) ?>
  <?= Alert::widget() ?>

<div class="page-title">
  <div class="title_left">
    <h3><?= Html::encode($this->title) ?></h3>
  </div>
</div>
<div class="clearfix"></div>
<div class="row">
  <div class="col-md-12 col-sm-12 col-xs-12">
    <div class="x_panel">
      <div class="x_title">
        <h2>Exercício cadastrado com sucesso</h2>
        <ul class="nav navbar-right panel_toolbox">
          <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
          </li>
        </ul>
        <div class="clearfix"></div>
      </div>
      <div class="x_content2">

        <?= DetailView::widget([
          'model' => $resumo,
          'attributes' => [
              ['attribute' => 'descricao', 'label' => 'Tema da avaliação:'],
              ['attribute' => 'nQuestoes', 'label' => 'Número de questões:'],
              ['attribute' => 'id', 'label' => 'ID do exercício:'],
          ],
        ]) ?>
        <p>
          <?= Html::a('Ver Todos os Exercícios', ['exercicios-index'], ['class' => 'btn btn-primary']) ?>
        </p>

      </div>
    </div>
  </div>
</div>
<div class="clearfix"></div>

views/administrar/exerciciosIndex.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\grid\GridView;
use yii\widgets\Breadcrumbs;
use app\widgets\Alert;
/* @var $this yii\web\View */
/* @var $searchModel frontend\models\ExerciciosSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Exercícios';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="exercicios-index">
    
    <?= Breadcrumbs::widget([
        'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
    ]) ?>
    <?= Alert::widget() ?>

    <h1><?= Html::encode($this->title) ?></h1>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <p>
        <?= Html::a('Importar Exercícios do Multiprova', ['exercicios-create'], ['class' => 'btn btn-success']) ?>
    </p>
    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            //['class' => 'yii\grid\SerialColumn'],
            ['attribute' => 'descricao', 'label' => 'Descrição do exercício:'],
            ['attribute' => 'id', 'label' => 'ID do exercício:'],
            [
                'class' => 'yii\grid\ActionColumn',
                'template' => '{update}{delete}',
                'urlCreator' => function ($action, $model, $key, $index, $thisa) {
                    //return string;                    
                    if ($action === "update"){
                        return Url::base().'/administrar/exercicios-update?id='.$key;
                    }
                    if ($action === "delete"){
                        return Url::base().'/administrar/exercicios-delete?id='.$key;
                    }
                },
            ],
        ],
    ]); ?>
</div>

views/administrar/exerciciosUpdate.php
<?php

use yii\helpers\Html;
use yii\widgets\Breadcrumbs;
use app\widgets\Alert;
/* @var $this yii\web\View */
/* @var $model frontend\models\Exercicios */

$this->title =  $model->descricao;
$this->params['breadcrumbs'][] = ['label' => 'Exercicios', 'url' => ['exercicios-index']];
$this->params['breadcrumbs'][] = ['label' => $model->descricao, 'url' => ['exercicios-view', 'id' => $model->id]];
?>
<div class="exercicios-update">

	<?= Breadcrumbs::widget([
	  'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
	]) ?>
	<?= Alert::widget() ?>

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('exercicios_form', [
        'model' => $model,
    ]) ?>

</div>

views/administrar/exerciciosView.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;
use yii\widgets\Breadcrumbs;
use app\widgets\Alert;
/* @var $this yii\web\View */
/* @var $model frontend\models\Exercicios */

$this->title = $model->descricao;
$this->params['breadcrumbs'][] = ['label' => 'Exercicios', 'url' => ['exercicios-index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="exercicios-view">

    <?= Breadcrumbs::widget([
        'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
    ]) ?>
    <?= Alert::widget() ?>

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Atualizar', ['exercicios-update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Excluir', ['exercicios-delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Tem certeza que deseja excluir esse exercício?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'descricao',
            'id',
            //'imagens',
            //'created_at',
        ],
    ]) ?>

</div>

views/administrar/exercicios_Form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model frontend\models\Exercicios */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="exercicios-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'descricao')->textInput(['maxlength' => true]) ?>

    <div class="form-group">
        <?= Html::submitButton('Atualizar Descrição', ['class' => 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/administrar/exercicios_Search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model frontend\models\ExerciciosSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="exercicios-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'user_id') ?>

    <?= $form->field($model, 'descricao') ?>

    <?= $form->field($model, 'evento_id') ?>

    <?= $form->field($model, 'imagens') ?>

    <?php // echo $form->field($model, 'created_at') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>